version: '3'
services:
  web:
    build: ./container
    command: php -S 0.0.0.0:8000 -t /root/app
    volumes:
      - ./app:/root/app
    ports:
      - "8000:8000"
      - "9000:9000"
  dev:
    build: ./container
    command: /bin/sh